### ISSUE TITLE
my IT section as OPML

### ISSUE THREAD

**Issue by Thomas-U** [vincode-io/FeedCompass#23]
hi Maurice,

[TU-IT-Subscriptions.opml.zip](https://github.com/vincode-io/FeedCompass/files/2988871/TU-IT-Subscriptions.opml.zip)

I maybe shall put it online at a later stage.

**Comment by vincode-io** [comment]
I apologize again.  I should have asked you to upload this to http://feedBase.io  As I mentioned in the NNW slack, we have plans to integrate more fully with feedBase and this is the best route to getting your OPML into Feed Compass.
